# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.5.2'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Check Hands_on_III.ipynb
        run: if [ -e Hands_on_III.ipynb ] ; then exit 0 ; else { echo missing Hands_on_III.ipynb ; exit 1 ; } ; fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Jupyter
        run: python -m pip install jupyter
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Hands_on_III.html
        run: quarto render Hands_on_III.ipynb --to html --embed-resources
      - name: Check Hands_on_III.html
        run: if [ -e Hands_on_III.html ] ; then exit 0 ; else { echo missing Hands_on_III.html ; exit 1 ; } ; fi